"$schema" = 'https://starship.rs/config-schema.json'
palette = "gruvbox_dark"

format = "$all"
right_format = """$time"""

# [username]

# [hostname]

[shlvl]
disabled = true
symbol = " "

[kubernetes]
disabled = true

[directory]
read_only = " 󰌾"
style = "bold bright-cyan"
truncate_to_repo = false
truncation_length = 2
truncation_symbol = ".../"

[vcsh]
disabled = true

[git_branch]
style = "bold bright-purple"
symbol = " "

# [git_commit]

# [git_state]

# [git_status]

[hg_branch]
disabled = true
symbol = " "

[docker_context]
symbol = " "

[package]
symbol = " "

[cmake]
disabled = true

[dart]
disabled = true
symbol = " "

[deno]
symbol = " "

[dotnet]
disabled = true

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[erlang]
disabled = true

[golang]
symbol = " "

[helm]
disabled = true

[java]
symbol = " "

[julia]
disabled = true
symbol = " "

[kotlin]
disabled = true

[nim]
disabled = true
symbol = " "

[nodejs]
detect_extensions = []

[ocaml]
disabled = true

[perl]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[purescript]
disabled = true

[python]
disabled = true
symbol = " "

[red]
disabled = true

[ruby]
disabled = true
symbol = " "

[rust]
symbol = " "

[scala]
disabled = true
symbol = " "

[swift]
disabled = true
symbol = "ﯣ "

[terraform]
disabled = true

[vlang]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true

[nix_shell]
disabled = true
symbol = " "

[conda]
disabled = true
symbol = " "

[memory_usage]
disabled = true
symbol = "󰍛 "

[aws]
format = "with [$symbol AWS](bold yellow) "
symbol = "󰸏"

[gcloud]
disabled = true

[openstack]
disabled = true

[env_var.AWS_PROFILE]
format = "with [$symbol AWS_PROFILE $env_value](bold yellow) "
symbol = "󰸏"
variable = "AWS_PROFILE"

[env_var.GH_TOKEN]
format = "with [$symbol GH_TOKEN](bold yellow) "
symbol = ""
variable = "GH_TOKEN"

[env_var.GITHUB_TOKEN]
format = "with [$symbol GITHUB_TOKEN](bold yellow) "
symbol = ""
variable = "GITHUB_TOKEN"

[env_var.DENO_DEPLOY_TOKEN]
format = "with [$symbol DENO_DEPLOY_TOKEN](bold yellow) "
symbol = ""
variable = "DENO_DEPLOY_TOKEN"

[env_var.NPM_TOKEN]
format = "with [$symbol NPM_TOKEN](bold yellow) "
symbol = ""
variable = "NPM_TOKEN"

[env_var.VERCEL_TOKEN]
format = "with [$symbol VERCEL_TOKEN](bold yellow) "
symbol = "▲"
variable = "VERCEL_TOKEN"

[env_var.FLY_ACCESS_TOKEN]
format = "with [$symbol FLY_ACCESS_TOKEN](bold yellow) "
symbol = ""
variable = "FLY_ACCESS_TOKEN"

[env_var.SUPABASE_ACCESS_TOKEN]
format = "with [$symbol SUPABASE_ACCESS_TOKEN](bold yellow) "
symbol = ""
variable = "SUPABASE_ACCESS_TOKEN"

[env_var.TURSO_API_TOKEN]
format = "with [$symbol TURSO_API_TOKEN](bold yellow) "
symbol = ""
variable = "TURSO_API_TOKEN"

[env_var.ASCIINEMA_REC]
format = "[$symbol rec](bold bright-red) "
symbol = "󰑋"
variable = "ASCIINEMA_REC"

[env_var.FRP_TOKEN]
format = "[$symbol FRP_TOKEN](bold yellow) "
symbol = "󱠾"
variable = "FRP_TOKEN"

[container]
disabled = true

[crystal]
disabled = true

[cmd_duration]
min_time = 5_000
style = "bold bright-yellow"

# [line_break]

[lua]
disabled = true

[jobs]
disabled = true

[battery]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
style = 'bright-blue'
time_format = "%r"

# [status]

# [shell]

[character]
error_symbol = "[✗](bold bright-red) "
success_symbol = "[➜](bold bright-green) "

[palettes.gruvbox_dark]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
purple = "#b16286"
cyan = "#689d6a"
white = "#ebdbb2"
bright-black = "#928374"
bright-red = "#fb4934"
bright-green = "#b8bb26"
bright-yellow = "#fabd2f"
bright-blue = "#83a598"
bright-purple = "#d3869b"
bright-cyan = "#8ec07c"
bright-white = "#fbf1c7"
orange = "#d65d0e"
