"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"
right_format = """$time"""

# [username]

# [hostname]

[shlvl]
disabled = true
symbol = "ï„  "

[kubernetes]
disabled = true

[directory]
read_only = " ï ½"
truncate_to_repo = false
truncation_length = 2
truncation_symbol = ".../"

[vcsh]
disabled = true

[git_branch]
symbol = "ï˜ "

# [git_commit]

# [git_state]

# [git_status]

[hg_branch]
disabled = true
symbol = "ï˜ "

[docker_context]
symbol = "ïŒˆ "

[package]
symbol = "ï£– "

[cmake]
disabled = true

[dart]
disabled = true
symbol = "î˜ "

# [deno]

[dotnet]
disabled = true

[elixir]
disabled = true
symbol = "î‰µ "

[elm]
disabled = true
symbol = "î˜¬ "

[erlang]
disabled = true

[golang]
symbol = "î˜§ "

[helm]
disabled = true

[java]
symbol = "î‰– "

[julia]
disabled = true
symbol = "î˜¤ "

[kotlin]
disabled = true

[nim]
disabled = true
symbol = "ïš¤ "

# [nodejs]

[ocaml]
disabled = true

[perl]
disabled = true
symbol = "î© "

[php]
disabled = true
symbol = "î˜ˆ "

[purescript]
disabled = true

[python]
disabled = true
symbol = "î˜† "

[red]
disabled = true

[ruby]
disabled = true
symbol = "îˆ¾ "

[rust]
disabled = true
symbol = "î¨ "

[scala]
disabled = true
symbol = "îœ· "

[swift]
disabled = true
symbol = "ï¯£ "

[terraform]
disabled = true

[vlang]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true

[nix_shell]
disabled = true
symbol = "ï‹œ "

[conda]
disabled = true
symbol = "ï„Œ "

[memory_usage]
disabled = true
symbol = "ï¡š "

[aws]
format = "with [$symbol AWS](bold dimmed yellow) "
symbol = "ï™ "

[gcloud]
disabled = true

[openstack]
disabled = true

[env_var.GH_TOKEN]
format = "with [$symbol GH_TOKEN](bold dimmed yellow) "
symbol = "îœ‰"
variable = "GH_TOKEN"

[env_var.GITHUB_TOKEN]
format = "with [$symbol GITHUB_TOKEN](bold dimmed yellow) "
symbol = "îœ‰"
variable = "GITHUB_TOKEN"

[env_var.DENO_DEPLOY_TOKEN]
format = "with [$symbol DENO_DEPLOY_TOKEN](bold dimmed yellow) "
symbol = "ğŸ¦•"
variable = "DENO_DEPLOY_TOKEN"

[env_var.NPM_TOKEN]
format = "with [$symbol NPM_TOKEN](bold dimmed yellow) "
symbol = "î˜–"
variable = "NPM_TOKEN"

[env_var.ASCIINEMA_REC]
format = "[$symbol rec](bold dimmed red) "
symbol = "ï¥Š"
variable = "ASCIINEMA_REC"

[container]
disabled = true

[crystal]
disabled = true

[cmd_duration]
min_time = 5_000

# [line_break]

[lua]
disabled = true

[jobs]
disabled = true

[battery]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
style = 'dimmed cyan'
time_format = "%r"

# [status]

# [shell]

[character]
error_symbol = "[âœ—](bold red) "
success_symbol = "[âœ](bold green) "
